=== Moskovetc/xml_json_task/example.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="shop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="name"/>
							<xs:element name="subCategory" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name"/>
										<xs:element name="product" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="name"/>
													<xs:element type="xs:string" name="manufacturer"/>
													<xs:element name="model">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="[a-zA-Z]{3}[0-9]{3}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element type="xs:date" name="manufactureDate"/>
													<xs:element name="color">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="white"/>
															<xs:enumeration value="yellow"/>
															<xs:enumeration value="black"/>
															<xs:enumeration value="blue"/>
															<xs:enumeration value="red"/>
															<xs:enumeration value="green"/>
															<xs:enumeration value="pink"/>
														</xs:restriction>
													</xs:simpleType>
                                                    </xs:element>
													<xs:element name="price">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="0"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="quantity" default="0">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="0"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Moskovetc/xml_json_task/out.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Only EDA shop" xsi:schemaLocation="example.xsd">
    <category>
        <name>Food</name>
        <subCategory>
            <name>Meat</name>
            <product>
                <name>Pork</name>
                <manufacturer>Pork Co</manufacturer>
                <model>mea001</model>
                <manufactureDate>2018-11-10</manufactureDate>
                <color>pink</color>
                <price>250</price>
                <quantity>5</quantity>
            </product>
            <product>
                <name>chiken</name>
                <manufacturer>chiken Co</manufacturer>
                <model>mea002</model>
                <manufactureDate>2018-11-09</manufactureDate>
                <color>white</color>
                <price>200</price>
                <quantity>15</quantity>
            </product>
            <product>
                <name>cow</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mea003</model>
                <manufactureDate>2018-11-12</manufactureDate>
                <color>pink</color>
                <price>210</price>
                <quantity>20</quantity>
            </product>
        </subCategory>
        <subCategory>
            <name>Milk</name>
            <product>
                <name>milk</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mil001</model>
                <manufactureDate>2018-11-02</manufactureDate>
                <color>white</color>
                <price>40</price>
                <quantity>60</quantity>
            </product>
            <product>
                <name>cheese</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mil002</model>
                <manufactureDate>2018-11-08</manufactureDate>
                <color>yellow</color>
                <price>120</price>
                <quantity>30</quantity>
            </product>
            <product>
                <name>curd</name>
                <manufacturer>Curd Factory Co</manufacturer>
                <model>mil003</model>
                <manufactureDate>2018-10-10</manufactureDate>
                <color>white</color>
                <price>132</price>
                <quantity>102</quantity>
            </product>
        </subCategory>
    </category>
    <category>
        <name>Food</name>
        <subCategory>
            <name>Meat</name>
            <product>
                <name>Pork</name>
                <manufacturer>Pork Co</manufacturer>
                <model>mea001</model>
                <manufactureDate>2018-11-10</manufactureDate>
                <color>pink</color>
                <price>250</price>
                <quantity>5</quantity>
            </product>
            <product>
                <name>chiken</name>
                <manufacturer>chiken Co</manufacturer>
                <model>mea002</model>
                <manufactureDate>2018-11-09</manufactureDate>
                <color>white</color>
                <price>200</price>
                <quantity>15</quantity>
            </product>
            <product>
                <name>cow</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mea003</model>
                <manufactureDate>2018-11-12</manufactureDate>
                <color>pink</color>
                <price>210</price>
                <quantity>20</quantity>
            </product>
        </subCategory>
        <subCategory>
            <name>Milk</name>
            <product>
                <name>milk</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mil001</model>
                <manufactureDate>2018-11-02</manufactureDate>
                <color>white</color>
                <price>40</price>
                <quantity>60</quantity>
            </product>
            <product>
                <name>cheese</name>
                <manufacturer>Fermer Co</manufacturer>
                <model>mil002</model>
                <manufactureDate>2018-11-08</manufactureDate>
                <color>yellow</color>
                <price>120</price>
                <quantity>30</quantity>
            </product>
            <product>
                <name>curd</name>
                <manufacturer>Curd Factory Co</manufacturer>
                <model>mil003</model>
                <manufactureDate>2018-10-10</manufactureDate>
                <color>white</color>
                <price>132</price>
                <quantity>102</quantity>
            </product>
        </subCategory>
    </category>
</shop>
